# version: '3.1'

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    ports: ["3306:3306"]
    env_file: .env
    secrets:
      - DB_PASSWORD
      - DB_ROOT_PASSWORD
    networks: [inception]
    volumes: [/home/$USER/data/mariadb:/var/lib/mysql]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports: ["443:443"]
    env_file: .env
    networks: [inception]
    volumes: ["/home/$USER/data/wordpress:/var/www/html/wordpress"]
    depends_on:
      wordpress:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:443", "-k"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    ports: ["9000:9000"]
    env_file: .env
    secrets:
      - DB_PASSWORD
      - DB_ROOT_PASSWORD
      - WP_PASS
      - WP_PASS2
    networks: [inception]
    volumes: ["/home/$USER/data/wordpress:/var/www/html/wordpress"]
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s






#A bridge network creates an internal network within Docker where containers can communicate with each.
networks:
  inception:
    driver: bridge

secrets:
  DB_PASSWORD:
    file: ../secrets/db_password.txt
  DB_ROOT_PASSWORD:
    file: ../secrets/db_root_password.txt
  WP_PASS:
    file: ../secrets/credentials.txt
  WP_PASS2:
    file: ../secrets/credentials.txt

volumes:
  wordpress:
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/wordpress
  mariadb:
    driver_opts:
      o: bind
      type: none
      device: /home/$USER/data/mariadb