services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    ports: ["3306:3306"]
    env_file: .env
    secrets:
      - DB_PASSWORD
      - DB_ROOT_PASSWORD
    networks: ["inception"]
    volumes: ["${MARIADB_DIR}:/var/lib/mysql"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 3s

  
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports: ["443:443"]
    env_file: .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    networks: ["inception"]
    volumes:
      - "${WORDPRESS_DIR}:/var/www/html/wordpress"
      - "ssl_certs:/etc"
    depends_on:
      wordpress:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 3s
      timeout: 30s
      retries: 3

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    ports: ["9000:9000"]
    env_file: .env
    secrets:
      - DB_PASSWORD
      - CREDENTIALS
    networks: ["inception"]
    volumes: ["${WORDPRESS_DIR}:/var/www/html/wordpress"]
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php-fpm83", "-t"]
      interval: 3s
      timeout: 30s
      retries: 3



networks:
  inception:
    driver: bridge

secrets:
  DB_PASSWORD:
    file: ../secrets/db_password.txt
  DB_ROOT_PASSWORD:
    file: ../secrets/db_root_password.txt
  CREDENTIALS:
    file: ../secrets/credentials.txt

volumes:
  wordpress:
    driver_opts:
      o: bind
      type: none
      device: ${WORDPRESS_DIR}
  mariadb:
    driver_opts:
      o: bind
      type: none
      device: ${MARIADB_DIR}
  ssl_certs:
    driver_opts:
      o: bind
      type: none
      device: ${SSL_DIR}